// <auto-generated />
using System;
using ConsoleApp5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Iss.AvanMagazinOnline.DB.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20230609105422_Sixth")]
    partial class Sixth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Iss.AvanMagazinOnline.DB.Models.CategorieProdus", b =>
                {
                    b.Property<int>("CategorieProdusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategorieProdusId"));

                    b.Property<string>("DenumireCategorieProdus")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ICalculator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValueSql("host_name()");

                    b.Property<DateTime?>("IData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("IUtilizator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValueSql("suser_sname()");

                    b.Property<byte[]>("Rv")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UCalculator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValueSql("host_name()");

                    b.Property<DateTime?>("UData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("UUtilizator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValueSql("suser_sname()");

                    b.HasKey("CategorieProdusId");

                    b.ToTable("tnCategorieProdus");
                });

            modelBuilder.Entity("Iss.AvanMagazinOnline.DB.Models.Producator", b =>
                {
                    b.Property<int>("ProducatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProducatorId"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("DataInceput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("DataSfarsit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("'2078-12-31 00:00:00.0000000'");

                    b.Property<string>("ICalculator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValueSql("host_name()");

                    b.Property<DateTime?>("IData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("IUtilizator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValueSql("suser_sname()");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("ProducatorIdCt")
                        .HasColumnType("int");

                    b.Property<byte[]>("Rv")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UCalculator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValueSql("host_name()");

                    b.Property<DateTime?>("UData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("UUtilizator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValueSql("suser_sname()");

                    b.HasKey("ProducatorId");

                    b.ToTable("tProducator");
                });

            modelBuilder.Entity("Iss.AvanMagazinOnline.DB.Models.Produs", b =>
                {
                    b.Property<int>("ProdusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdusId"));

                    b.Property<int>("CategorieProdusId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostProdus")
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateTime>("DataInceput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DataSfarsit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("'2078-12-31 00:00:00.0000000'");

                    b.Property<string>("DenumireProdus")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("DescriereProdus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICalculator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValueSql("host_name()");

                    b.Property<DateTime?>("IData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("IUtilizator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValueSql("suser_sname()");

                    b.Property<int?>("ProdusIdCt")
                        .HasColumnType("int");

                    b.Property<byte[]>("Rv")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UCalculator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValueSql("host_name()");

                    b.Property<DateTime?>("UData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("UUtilizator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValueSql("suser_sname()");

                    b.HasKey("ProdusId");

                    b.HasIndex("CategorieProdusId");

                    b.ToTable("tProdus");
                });

            modelBuilder.Entity("Iss.AvanMagazinOnline.DB.Models.Produs", b =>
                {
                    b.HasOne("Iss.AvanMagazinOnline.DB.Models.CategorieProdus", "CategorieProdus")
                        .WithMany("Produse")
                        .HasForeignKey("CategorieProdusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AvnLeanring_tProdus_CategorieProdus");

                    b.Navigation("CategorieProdus");
                });

            modelBuilder.Entity("Iss.AvanMagazinOnline.DB.Models.CategorieProdus", b =>
                {
                    b.Navigation("Produse");
                });
#pragma warning restore 612, 618
        }
    }
}
